Repository Opteo/google-ads-api, pull requests merged in 2019-04, with the labels that each got.

#31 Remove unused errors codes
  src/error.ts
Labels: enhancement

#23 fix(utils): better error message when "val" field is undefined
  src/tests/utils.test.ts
  src/utils.ts
Labels: enhancement

#21 feat(utils): added support for single constraint object
  src/types.ts
Labels: enhancement :tada:

#38 Global customer mutate method
  README.md
  package.json
  src/customer.ts
  src/error.ts
  src/services/customer.ts
  src/services/service.ts
  src/tests/customer.test.ts
  src/types.ts
Labels: enhancement :tada:, feature request :bulb:
