Repository Opteo/google-ads-api, pull requests merged in 2020-06, with the labels that each got.

#130 feat(create-customer): Add use of CreateCustomerClient flow
  .example.env
  .gitignore
  examples/account_management/create_sub_account.js
  src/client.ts
  src/customer.ts
  src/grpc.ts
  src/services/customer.ts
  src/test_utils.ts
  src/tests/customer.test.ts
  src/types.ts
Labels: enhancement :tada:

#134 feat(report): added support for specifying summary row setting
  package.json
  src/customer.ts
  src/grpc.ts
  src/services/customer.ts
  src/services/service.ts
  src/tests/error.test.ts
  src/tests/report.test.ts
  src/types.ts
  yarn.lock
Labels: enhancement :tada:

#132 Add GoogleAdsApi.listAccessibleCustomers() method
  src/client.ts
  src/services/accessible_customers.ts
  src/services/customer.ts
Labels: enhancement :tada:

#141 test(report): added summary row test for #140
  src/tests/report.test.ts
Labels: enhancement :tada:

#143 chore(deps): upgraded google-ads-node to 1.15.5
  package.json
  src/services/service.ts
  src/tests/customer.test.ts
  yarn.lock
Labels: enhancement :tada:, next release 🚀

#144 chore(deps): upgraded google-ads-node to 1.15.6
  package.json
  yarn.lock
Labels: bug :warning:, next release 🚀

#145 chore(deps): upgraded google-ads-node to 1.15.7
  package.json
  yarn.lock
Labels: dependencies, next release 🚀
